name: multistep
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - java-jdk==8.0.112
  - python=3.6
  - pyspark==2.2.1
  - requests
  - click
  - pip:
    - tensorflow==1.13.1
    - keras==2.2.4
    - mlflow>=1.0
